apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: my-postgres-cluster
  namespace: postgres-operator
spec:
  postgresVersion: 15
  instances:
      replicas: 3
  monitoring:
    enablePodMonitor: true
    exporter:
      image: quay.io/prometheuscommunity/postgres-exporter:latest
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          max_connections: "300"
          shared_buffers: "256MB"

